apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: bXlkYg==       # base64 encoded value of "mydb"
  mysql-username: bXlkYg==       # base64 encoded value of "mydb"
  mysql-password: bXlkYg==       # base64 encoded value of "mydb"
  mysql-database: bXlkYg==       # base64 encoded value of "mydb"

